//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolFight
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminMail
    {
        public int IdAdminMail { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public int IdAdmin { get; set; }
        public int IdChampion { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Champion Champion { get; set; }
    }
}
