//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionType
    {
        public ChampionType()
        {
            this.Champions = new HashSet<Champion>();
        }
    
        public int IdChampionType { get; set; }
        public string Nation { get; set; }
        public string Name { get; set; }
        public string ImageLink { get; set; }
        public Nullable<int> HP { get; set; }
        public Nullable<int> AttackDamage { get; set; }
        public Nullable<int> AbilityDamage { get; set; }
        public Nullable<int> AttackSpeed { get; set; }
        public Nullable<int> Armor { get; set; }
        public Nullable<int> MagicResist { get; set; }
    
        public virtual ICollection<Champion> Champions { get; set; }
    }
}
