//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Champion
    {
        public Champion()
        {
            this.AdminMails = new HashSet<AdminMail>();
            this.Inventories = new HashSet<Inventory>();
            this.LogBattles = new HashSet<LogBattle>();
            this.LogBattles1 = new HashSet<LogBattle>();
            this.LogBattles2 = new HashSet<LogBattle>();
            this.LogFarms = new HashSet<LogFarm>();
            this.LogJungles = new HashSet<LogJungle>();
            this.Mails = new HashSet<Mail>();
            this.Mails1 = new HashSet<Mail>();
        }
    
        public int IdChampion { get; set; }
        public int IdChampionType { get; set; }
        public Nullable<int> Gold { get; set; }
        public Nullable<int> BanCooldown { get; set; }
    
        public virtual ICollection<AdminMail> AdminMails { get; set; }
        public virtual User User { get; set; }
        public virtual Ranking Ranking { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual ChampionType ChampionType { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<LogBattle> LogBattles { get; set; }
        public virtual ICollection<LogBattle> LogBattles1 { get; set; }
        public virtual ICollection<LogBattle> LogBattles2 { get; set; }
        public virtual ICollection<LogFarm> LogFarms { get; set; }
        public virtual ICollection<LogJungle> LogJungles { get; set; }
        public virtual ICollection<Mail> Mails { get; set; }
        public virtual ICollection<Mail> Mails1 { get; set; }
    }
}
