//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogBattle
    {
        public int IdLogBattle { get; set; }
        public int IdAttacker { get; set; }
        public int IdDefender { get; set; }
        public Nullable<int> StartTime { get; set; }
        public Nullable<int> Gold { get; set; }
        public string Report { get; set; }
        public int IdWinner { get; set; }
    
        public virtual Champion Champion { get; set; }
        public virtual Champion Champion1 { get; set; }
        public virtual Champion Champion2 { get; set; }
    }
}
