//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolFightProjekat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        public Admin()
        {
            this.AdminMails = new HashSet<AdminMail>();
        }
        [Required(ErrorMessage = "Mora se unijet id (za sada)")]
        public int IdAdmin { get; set; }
        [ExcludeChar("/.,!@#$%", ErrorMessage = "Ime ne smije sadržavati /.,!@#$% karaktere.")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Mora se unijeti password")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Mora se unijeti e-mail")]
        public string eMail { get; set; }
    
        public virtual ICollection<AdminMail> AdminMails { get; set; }
    }
}
