//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolFightProjekat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    
    public partial class admin
    {
        public admin()
        {
            this.porukes = new HashSet<poruke>();
        }
         [Required]
        public int idAdmina { get; set; }
         [ExcludeChar("/.,!@#$%", ErrorMessage = "Ime ne smije sadržavati /.,!@#$% karaktere.")]
        public string Username { get; set; }
         [Required]
        public string Password { get; set; }
        public string eMail { get; set; }
    
        public virtual ICollection<poruke> porukes { get; set; }
    }
}
