//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolFightProjekat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class championi
    {
        public championi()
        {
            this.inventories = new HashSet<inventory>();
            this.izvjestajiborbis = new HashSet<izvjestajiborbi>();
            this.izvjestajiborbis1 = new HashSet<izvjestajiborbi>();
            this.izvjestajiborbis2 = new HashSet<izvjestajiborbi>();
            this.logaktivnostis = new HashSet<logaktivnosti>();
            this.porukes = new HashSet<poruke>();
            this.porukes1 = new HashSet<poruke>();
            this.rankstatistikas = new HashSet<rankstatistika>();
            this.skilovis = new HashSet<skilovi>();
        }
    
        public int idChampiona { get; set; }
        public int Korisnici_idKorisnika { get; set; }
        public string Nacija { get; set; }
        public int SviChampioni_idSviChampioni { get; set; }
        public string Gold { get; set; }
        public string DaLiJeAktivan { get; set; }
    
        public virtual korisnici korisnici { get; set; }
        public virtual svichampioni svichampioni { get; set; }
        public virtual ICollection<inventory> inventories { get; set; }
        public virtual ICollection<izvjestajiborbi> izvjestajiborbis { get; set; }
        public virtual ICollection<izvjestajiborbi> izvjestajiborbis1 { get; set; }
        public virtual ICollection<izvjestajiborbi> izvjestajiborbis2 { get; set; }
        public virtual ICollection<logaktivnosti> logaktivnostis { get; set; }
        public virtual ICollection<poruke> porukes { get; set; }
        public virtual ICollection<poruke> porukes1 { get; set; }
        public virtual ICollection<rankstatistika> rankstatistikas { get; set; }
        public virtual ICollection<skilovi> skilovis { get; set; }
    }
}
