//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolFightProjekat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int idItema { get; set; }
        public int Championi_idChampiona { get; set; }
        public int SviItemi_idSviItem { get; set; }
        public Nullable<bool> DaLiJeAktiviran { get; set; }
    
        public virtual championi championi { get; set; }
        public virtual sviitemi sviitemi { get; set; }
    }
}
