//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolFightProjekat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class izvjestajiborbi
    {
        public int idIzvjestajiBorbi { get; set; }
        public int idNapadaca { get; set; }
        public int idBranioca { get; set; }
        public string VrijemeNapada { get; set; }
        public Nullable<int> OstvareniGold { get; set; }
        public string IzvjestajBorbe { get; set; }
        public int idPobjednika { get; set; }
    
        public virtual championi championi { get; set; }
        public virtual championi championi1 { get; set; }
        public virtual championi championi2 { get; set; }
    }
}
