//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolFightProjekat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class korisnici
    {
        public korisnici()
        {
            this.championis = new HashSet<championi>();
        }

        public int idKorisnika { get; set; }
        [Required(ErrorMessage = "You know you need a username, right?", AllowEmptyStrings = false)]
        public string Username { get; set; }
        [Required(ErrorMessage = "Choose a password, make it strong for safety!", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        [StringLength(50, MinimumLength = 7, ErrorMessage = "Make it at least 7 characters!")]
        public string Password { get; set; }
        // Compare won't bind, fix later.
        //[Compare("Password",ErrorMessage="Just repeat the damn password."]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string ConfirmPassword { get; set; }
        public string eMail { get; set; }

        public virtual ICollection<championi> championis { get; set; }
    }
}