//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolFightProjekat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logaktivnosti
    {
        public int idLogAktivnosti { get; set; }
        public int Championi_idChampiona { get; set; }
        public int LogFarmanja_idLogFarmanja { get; set; }
        public int LogJunglanja_idLogJunglanja { get; set; }
    
        public virtual championi championi { get; set; }
        public virtual logfarmanja logfarmanja { get; set; }
        public virtual logjunglanja logjunglanja { get; set; }
    }
}
