//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolFightProjekat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logfarmanja
    {
        public logfarmanja()
        {
            this.logaktivnostis = new HashSet<logaktivnosti>();
        }
    
        public int idLogFarmanja { get; set; }
        public string PocetakFarmanja { get; set; }
        public Nullable<int> KojiPutUDanu { get; set; }
        public Nullable<int> DobiveniGold { get; set; }
        public string Statistika { get; set; }
    
        public virtual ICollection<logaktivnosti> logaktivnostis { get; set; }
    }
}
