//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolFightProjekat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lolfighdatabaseEntities : DbContext
    {
        public lolfighdatabaseEntities()
            : base("name=lolfighdatabaseEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<AdminMail> AdminMails { get; set; }
        public DbSet<Champion> Champions { get; set; }
        public DbSet<ChampionType> ChampionTypes { get; set; }
        public DbSet<Inventory> Inventories { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<LogBattle> LogBattles { get; set; }
        public DbSet<LogFarm> LogFarms { get; set; }
        public DbSet<LogJungle> LogJungles { get; set; }
        public DbSet<Mail> Mails { get; set; }
        public DbSet<Ranking> Rankings { get; set; }
        public DbSet<Skill> Skills { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
