//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolFightProjekat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lolfightbazaEntities : DbContext
    {
        public lolfightbazaEntities()
            : base("name=lolfightbazaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
        public DbSet<championi> championis { get; set; }
        public DbSet<inventory> inventories { get; set; }
        public DbSet<izvjestajiborbi> izvjestajiborbis { get; set; }
        public DbSet<korisnici> korisnicis { get; set; }
        public DbSet<logaktivnosti> logaktivnostis { get; set; }
        public DbSet<logfarmanja> logfarmanjas { get; set; }
        public DbSet<logjunglanja> logjunglanjas { get; set; }
        public DbSet<poruke> porukes { get; set; }
        public DbSet<rankstatistika> rankstatistikas { get; set; }
        public DbSet<skilovi> skilovis { get; set; }
        public DbSet<svichampioni> svichampionis { get; set; }
        public DbSet<sviitemi> sviitemis { get; set; }
    }
}
