//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolFightProjekat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class poruke
    {
        public int idPoruke { get; set; }
        public int idPosiljaoca { get; set; }
        public int idPrimaoca { get; set; }
        public Nullable<int> Admin_idAdmina { get; set; }
        public string NaslovPoruke { get; set; }
        public string VrijemePoruke { get; set; }
        public string TekstPoruke { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual championi championi { get; set; }
        public virtual championi championi1 { get; set; }
    }
}
