//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolFightProjekat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rankstatistika
    {
        public int idRankStatistika { get; set; }
        public int Championi_idChampiona { get; set; }
        public string NafarmaniGold { get; set; }
        public string OpljackaniGold { get; set; }
    
        public virtual championi championi { get; set; }
    }
}
