//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolFightProjekat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skilovi
    {
        public int idSkila { get; set; }
        public int Championi_idChampiona { get; set; }
        public Nullable<int> HP { get; set; }
        public Nullable<int> AttackDmg { get; set; }
        public Nullable<int> AbilityPowerDmg { get; set; }
        public Nullable<int> AttackSpeed { get; set; }
        public Nullable<int> Armor { get; set; }
        public Nullable<int> MagicResist { get; set; }
        public Nullable<int> CritChance { get; set; }
        public Nullable<int> ArmorPen { get; set; }
        public Nullable<int> MagicPen { get; set; }
    
        public virtual championi championi { get; set; }
    }
}
