//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolFightProjekat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sviitemi
    {
        public sviitemi()
        {
            this.inventories = new HashSet<inventory>();
        }
    
        public int idSviItem { get; set; }
        public string Naziv { get; set; }
        public Nullable<int> Cijena { get; set; }
        public Nullable<int> HP { get; set; }
        public Nullable<int> AttackDmg { get; set; }
        public Nullable<int> AbilityPower { get; set; }
        public Nullable<int> AttackSpeed { get; set; }
        public Nullable<int> Armor { get; set; }
        public Nullable<int> MagicResist { get; set; }
        public Nullable<int> CritChance { get; set; }
        public Nullable<int> ArmorPen { get; set; }
        public Nullable<int> HealAmount { get; set; }
        public string linkSlike { get; set; }
    
        public virtual ICollection<inventory> inventories { get; set; }
    }
}
